package com.wadia.beans;

// Generated 30 ao�t 2012 18:58:08 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EContractData generated by hbm2java
 */
@Entity
@Table(name = "e_contract_data")
public class EContractData implements java.io.Serializable {

    private Integer contratId;
    private String resurceId;
    private String contractType;
    private Date hireDate;
    private Date contractStartDate;
    private Date contractEndDate;
    private String contractStatus;
    private String description;

    public EContractData() {
    }

    public EContractData(String resurceId) {
	this.resurceId = resurceId;
    }

    public EContractData(String resurceId, String contractType, Date hireDate, Date contractStartDate,
	    Date contractEndDate, String contractStatus, String description) {
	this.resurceId = resurceId;
	this.contractType = contractType;
	this.hireDate = hireDate;
	this.contractStartDate = contractStartDate;
	this.contractEndDate = contractEndDate;
	this.contractStatus = contractStatus;
	this.description = description;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "CONTRAT_Id", unique = true, nullable = false)
    public Integer getContratId() {
	return this.contratId;
    }

    public void setContratId(Integer contratId) {
	this.contratId = contratId;
    }

    @Column(name = "RESURCE_ID", nullable = false, length = 500)
    public String getResurceId() {
	return this.resurceId;
    }

    public void setResurceId(String resurceId) {
	this.resurceId = resurceId;
    }

    @Column(name = "CONTRACT_TYPE", length = 100)
    public String getContractType() {
	return this.contractType;
    }

    public void setContractType(String contractType) {
	this.contractType = contractType;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "HIRE_DATE", length = 10)
    public Date getHireDate() {
	return this.hireDate;
    }

    public void setHireDate(Date hireDate) {
	this.hireDate = hireDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "CONTRACT_START_DATE", length = 10)
    public Date getContractStartDate() {
	return this.contractStartDate;
    }

    public void setContractStartDate(Date contractStartDate) {
	this.contractStartDate = contractStartDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "CONTRACT_END_DATE", length = 10)
    public Date getContractEndDate() {
	return this.contractEndDate;
    }

    public void setContractEndDate(Date contractEndDate) {
	this.contractEndDate = contractEndDate;
    }

    @Column(name = "CONTRACT_STATUS", length = 100)
    public String getContractStatus() {
	return this.contractStatus;
    }

    public void setContractStatus(String contractStatus) {
	this.contractStatus = contractStatus;
    }

    @Column(name = "DESCRIPTION", length = 500)
    public String getDescription() {
	return this.description;
    }

    public void setDescription(String description) {
	this.description = description;
    }

    @Override
    public String toString() {
	return "EContractData [" + (contratId != null ? "contratId=" + contratId + ", " : "")
		+ (resurceId != null ? "resurceId=" + resurceId + ", " : "")
		+ (contractType != null ? "contractType=" + contractType + ", " : "")
		+ (hireDate != null ? "hireDate=" + hireDate + ", " : "")
		+ (contractStartDate != null ? "contractStartDate=" + contractStartDate + ", " : "")
		+ (contractEndDate != null ? "contractEndDate=" + contractEndDate + ", " : "")
		+ (contractStatus != null ? "contractStatus=" + contractStatus + ", " : "")
		+ (description != null ? "description=" + description : "") + "]";
    }

}
